### ISSUE TITLE
[Fix for inaccurate measure definitions] Include filters defined within a measures' LookML to the 'About this Field' section in the Data Dictionary

### ISSUE THREAD

**Issue by fiona-cummings** [looker-open-source/app-data-dictionary#76]
I'm hoping this is a relatively simple add - can anyone help with including the filters defined within the LookML of a measure to the information included in the Looker Data Dictionary? Without including the filters the definitions for any measures with filters are inaccurate and misleading. Here's an example:

**LookML: I** define the measure with filters for the measure Assigned Requests Count here:

![Look ML example](https://user-images.githubusercontent.com/87833658/170781702-17d82b37-2643-4e60-95f9-45d4e4e3aa92.jpg)

**Data Dictionary:** There is no filter information included within the Data Dictionary for the same measure. This makes it look like the measure is a count distinct on all interaction_ids when it is actually a count distinct filtered on three separate dimensions.

![data dictionary example](https://user-images.githubusercontent.com/87833658/170781760-0fec3425-a700-404d-b404-72a52c7dba0d.jpg)

**Ask:** To fix this I want to add a section to the 'About this Field' section in the data dictionary that includes the filter information - what is the simplest way to do this?

**Comment by Itzaprado** [comment]
The filters are related to the measures and dimensions of the explores, and in the data dictionary we show the metadata of the field, so I consider it unnecesary to add the filters there, it could generate conflicts when two or more people add different filters to the field.
