### ISSUE TITLE
Bad Transaction Key in front of  model name

### ISSUE THREAD

**Issue by Kwschramm** [looker-open-source/app-data-dictionary#80]
Hello.  My client is using the marketplace version of the data dictionary but someone here mentioned to submit this question here.  Is there a reason that we see this in front of the model name
![Capture](https://user-images.githubusercontent.com/29603481/195452528-bfa96f16-0e23-4a40-bf1c-8a26a9e2d578.PNG)

**Comment by AnnaSerova** [comment]
Hi, we can't reproduce this issue anymore, so I'm closing it.
